#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Tue Apr  9 15:53:53 2019
#

import wx
import Departmentsql


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    x1 = 0
    x2 = 0


    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, " id ")
        self.text_ctrl_1.Bind(wx.EVT_TEXT,self.EVT1)
        # x1 = self.text_ctrl_1.GetValue()

        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, " name ")
        self.text_ctrl_2.Bind(wx.EVT_TEXT, self.EVT2)
        # x2 = self.text_ctrl_1.GetStringSelection()


        self.button_1 = wx.Button(self, wx.ID_ANY, "Add Id")
        self.button_1.Bind(wx.EVT_BUTTON,self.Onclik)


        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        label_1 = wx.StaticText(self, wx.ID_ANY, "Dept_id")
        sizer_3.Add(label_1, 0, 0, 0)
        sizer_3.Add(self.text_ctrl_1, 1, 0, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add((0, 0), 0, 0, 0)
        label_2 = wx.StaticText(self, wx.ID_ANY, "Dept_name")
        sizer_4.Add(label_2, 0, 0, 0)
        sizer_4.Add(self.text_ctrl_2, 2, 0, 0)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_2.Add(self.button_1, 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def EVT1(self,e):
        self.x1 = e.GetString()
        # print("HEla")
        # print(x1)


    def EVT2(self,e):
        self.x2 = e.GetString()


    def Onclik(self,e):
        print(self.x1)
        print(self.x2)
        # print("  x1 "+self.x1+" x2 "+self.x2)
        # z = input(" main pro z ")
        if self.x1==0 or self.x2==0:
            yesNoBox1 = wx.MessageDialog(None, "Invalid input", 'Question', wx.OK)
            yesNoAnswer1 = yesNoBox1.ShowModal()
            yesNoBox1.Destroy()
            self.Destroy()
            app = MyApp(0)
            app.MainLoop()
            # self.close()


        x , li_st= Departmentsql.getdaat(self.x1,self.x2)
        lis_t=[]
        # print(x)
        # print(li_st)
        for i in li_st:
            i = (str)(i)
            lis_t.append(i)
            lis_t.append(" , ")
        li_st ="".join(lis_t)
        # print(li_st)
        # z = input()
        if x == 1:
            y
            if yesNoAnswer == wx.ID_YES:
                # app.destroy()
                # app = MyApp()
                # app.MainLoop()
                pass


            elif yesNoAnswer == wx.ID_NO:
                exit()esNoBox = wx.MessageDialog(None, 'THE ID YOU ARE ENTERING IS ALREADY PRESENT '+li_st+'\nPRESS yes to try again and no to stop', 'Question', wx.YES_NO)
            yesNoAnswer = yesNoBox.ShowModal()
            yesNoBox.Destroy()
        else:
            yesNoBox1 = wx.MessageDialog(None,"Done",'Question', wx.OK)
            yesNoAnswer1 = yesNoBox1.ShowModal()
            yesNoBox1.Destroy()
            exit()





# end of class MyFrame

class MyApp(wx.App):

    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    print("reached here2")
    app = MyApp(0)
    print("reaches here1")
    app.MainLoop()
